projectType: extension
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: -DdiscoverRuntimes.product=EE -DdiscoverRuntimes.minMuleVersion=4.2.0  -Dtest=none -DfailIfNoTests=false -DminVersion=4.3.0
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DdiscoverRuntimes.product=EE -DdiscoverRuntimes.minMuleVersion=4.6.0 -Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0
