projectType: extension
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: -DruntimeProduct=MULE_EE -DdiscoverRuntimes.minMuleVersion=4.2.0  -Dtest=none -DfailIfNoTests=false
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DruntimeProduct=MULE_EE -DdiscoverRuntimes.minMuleVersion=4.6.0 -Dtest=none -DfailIfNoTests=false
