projectType: extension
additionalTestConfigs:
  jdk17-4.9.x:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DfailIfNoTests=false -DminVersion=4.9.0 -DruntimeVersion=4.9.1
mavenAdditionalArgs: -DincludeSnapshots=false -DmunitMinMuleVersion=4.9.0 -DruntimeVersion=4.9.1 -DfailIfNoTests=false
jdkTool: OPEN-JDK17
